Including option to scope manager to namespace
ory/oathkeeper-maester pull request #51
Opened 2021-09-13 18:20 UTC by janiskemper

This PR would allow to run Oathkeeper maester namespace-scoped. 

To use this option one has to change RBAC configuration in the helm chart:
-  change ClusterRole to Role and ClusterRoleBinding to RoleBinding 
- add the environment variable ```NAMESPACE```

If no environment variable is given, the default is "" which means all namespaces in Kubernetes.

If you want, we can also do a PR to the helm chart repo.

2021-09-13 18:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/oathkeeper-maester?pullRequest=51) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/oathkeeper-maester?pullRequest=51) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/oathkeeper-maester?pullRequest=51) it.</sub>

2021-09-14 10:56 UTC, Demonsthere commented
Hi there, thanks for the PR! 
Sadly as you can see we were affected by some upstream change to kubebuilder, which broke our CI. We cannot merge this until that has been addressed :/

2021-09-14 12:40 UTC, Demonsthere commented
@janiskemper I have fixed the CI, could you please rebase your PR?

2021-09-15 06:06 UTC, Demonsthere commented
Could you please clean the PR up a bit? I see my changes in there, which should not be the case :)

2021-09-20 09:01 UTC, Demonsthere requested changes
The core change is minimal, and ok. Tested it, and works as expected :) 
Please clean the PR up (duplicated commits and conflicts) and we can merge it right away

2021-09-24 07:52 UTC, janiskemper commented
Sorry, I didn't see this duplicate commit. Should be fine now I guess!

2021-09-24 08:01 UTC, piotrmsc commented on main.go
> +		Namespace: os.Getenv("NAMESPACE"),
@janiskemper please add to the readme this 'feature&behaviour' :) I think others will look for it too

2021-09-24 08:18 UTC, Demonsthere approved these changes

2021-09-24 08:18 UTC, merged

2021-09-24 08:48 UTC, piotrmsc commented on main.go
> +		Namespace: os.Getenv("NAMESPACE"),
thank you :)